name: 6_12-test

on:
  # TODO: back to normal
  push:
  # only runs on main, every 6 hours. specify hours explicitly so scheduled runs can be offset and use a random minute.
  schedule:
    - cron: "46 1,7,13,19 * * *"

jobs:
  build-kernels:
    uses: ./.github/workflows/build-kernels.yml
    secrets: inherit

  integration-test:
    uses: ./.github/workflows/integration-tests.yml
    needs: build-kernels
    secrets: inherit
    with:
      repo-name: stable/6_12

  notify-job:
    runs-on: ubuntu-latest
    # TODO: put back main branch requirement: if: ${{ failure() && github.ref == 'refs/heads/main' }}
    if: ${{ failure() }}
    needs:
      - integration-test
    steps:
    - uses: actions/checkout@v2
    - name: Test step that fails
      run: exit 1
    - name: Discord Notification
      if: always()
      uses: Devlander-Software/discord-webhook-notifier-action@v1.0.1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
        status: ${{ needs.integration-test.result }}
        workflow: ${{ github.workflow }}
        job: integration-test
        repo: ${{ github.repository }}
        branch: ${{ github.ref_name }}
        commit: ${{ github.sha }}
        actor: ${{ github.actor }}
        run_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

        avatar_url: https://www.dictionary.com/e/wp-content/uploads/2018/03/thisisfine-1.jpg
        content: Testing Discord notification - 6.12 ci job failed.
        color_failure: 15548997
