name: bpf-next-test

on:
  # only runs on main, every 6 hours. specify hours explicitly so scheduled runs can be offset and use a random minute.
  schedule:
    - cron: "35 0,6,12,18 * * *"

jobs:
  build-kernels:
    uses: ./.github/workflows/build-kernels.yml
    secrets: inherit

  integration-test:
    uses: ./.github/workflows/integration-tests.yml
    needs: build-kernels
    secrets: inherit
    with:
      repo-name: bpf/bpf-next

  notify-job:
    runs-on: ubuntu-latest
    if: ${{ failure() && github.ref == 'refs/heads/main' }}
    needs:
      - integration-test
    steps:
    - uses: actions/checkout@v2
    - name: Discord Notification
      uses: devlander/discord-webhook-notifier-action@v1
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        avatar-url: https://www.dictionary.com/e/wp-content/uploads/2018/03/thisisfine-1.jpg
        content: bpf-next ci job failed.
        color: 15548997


